"""
Test script to verify that metadata columns are preserved in Total_demand.csv
generated by dynamic_dtn_optimization part 1.

This script:
1. Runs dynamic_dtn_optimization part 1
2. Checks if the required metadata columns are present in the generated Total_demand.csv
3. Runs dynamic_dtn_optimization part 2 to ensure it works without errors

Usage:
    python test_metadata_columns.py -s <scenario_path>
"""

import os
import sys
import pandas as pd
import argparse
import logging
from pathlib import Path

import cea.config
import cea.inputlocator
from cea.optimization_new.dynamic_dtn_optimization import DynamicDTNOptimizer
from cea.optimization_new.dynamic_dtn_optimization_part2 import main as dynamic_dtn_part2_main

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("test_metadata_columns")

def parse_args():
    parser = argparse.ArgumentParser(description="Test metadata columns preservation in dynamic DTN optimization")
    parser.add_argument('-s', '--scenario', help='Path to the scenario folder', required=True)
    return parser.parse_args()

def run_dynamic_dtn_part1(config):
    """Run dynamic DTN optimization part 1"""
    logger.info("Running dynamic DTN optimization part 1...")
    
    # Create a DynamicDTNOptimizer instance
    optimizer = DynamicDTNOptimizer(
        locator=cea.inputlocator.InputLocator(config.scenario),
        config=config
    )
    
    # Run the optimizer
    optimizer.run()
    
    logger.info("Dynamic DTN optimization part 1 completed successfully")
    return optimizer

def check_metadata_columns(optimizer):
    """Check if required metadata columns are present in Total_demand.csv"""
    logger.info("Checking for metadata columns in Total_demand.csv...")
    
    # Get the path to the temporary scenario's Total_demand.csv
    temp_scenario_path = optimizer.locator.get_dynamic_dtn_optimization_temp_scenario_folder()
    temp_demand_path = Path(temp_scenario_path) / "outputs" / "data" / "demand" / "Total_demand.csv"
    
    # Check if the file exists
    if not temp_demand_path.exists():
        logger.error(f"Total_demand.csv not found at: {temp_demand_path}")
        return False
    
    # Read the file
    total_demand = pd.read_csv(temp_demand_path)
    
    # Check for required metadata columns
    required_columns = ['Af_m2', 'Aroof_m2', 'GFA_m2', 'Aocc_m2', 'people0']
    missing_columns = [col for col in required_columns if col not in total_demand.columns]
    
    if missing_columns:
        logger.error(f"Missing metadata columns in Total_demand.csv: {missing_columns}")
        return False
    
    logger.info("All required metadata columns are present in Total_demand.csv")
    return True

def run_dynamic_dtn_part2(config):
    """Run dynamic DTN optimization part 2"""
    logger.info("Running dynamic DTN optimization part 2...")
    
    try:
        # Run dynamic DTN optimization part 2
        dynamic_dtn_part2_main(config)
        logger.info("Dynamic DTN optimization part 2 completed successfully")
        return True
    except Exception as e:
        logger.error(f"Error running dynamic DTN optimization part 2: {e}")
        return False

def main():
    """Main function"""
    # Parse command line arguments
    args = parse_args()
    
    # Create a configuration object
    config = cea.config.Configuration()
    config.scenario = args.scenario
    
    # Set network type to DH (can be changed to DC if needed)
    config.dynamic_dtn_optimization.network_type = "DH"
    
    # Run dynamic DTN optimization part 1
    optimizer = run_dynamic_dtn_part1(config)
    
    # Check if metadata columns are present
    metadata_columns_present = check_metadata_columns(optimizer)
    
    if not metadata_columns_present:
        logger.error("Metadata columns check failed. Aborting test.")
        return 1
    
    # Run dynamic DTN optimization part 2
    part2_success = run_dynamic_dtn_part2(config)
    
    if not part2_success:
        logger.error("Dynamic DTN optimization part 2 failed. Test failed.")
        return 1
    
    logger.info("Test completed successfully. Metadata columns are preserved and part 2 runs without errors.")
    return 0

if __name__ == "__main__":
    sys.exit(main())