#!/usr/bin/env python
"""
Building Clustering Script for DTN Phased Optimization

This script clusters buildings based on annual heat demand (column "QH_sys_MWhyr" in Total_demand.csv)
and building proximity. It also reserves the existing district thermal network (DTN) buildings:
either automatically (Option 1: reading the nodes shapefile from the existing network layout)
or manually (Option 2: using a user-provided CSV file with building IDs).

Outputs are saved as CSV and a shapefile in the CEA output folder.
"""

__author__ = "Fan Ut Chang"
__copyright__ = "Copyright 2025"
__credits__ = ["Fan Ut Chang"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "NA"
__email__ = "changf@ethz.ch"
__status__ = "Production"

# Standard libraries
import os
import sys
import warnings

# Data handling libraries
import pandas as pd
import numpy as np

# Geospatial data handling libraries
import geopandas as gpd
from shapely.geometry import Point

# Clustering libraries
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Visualization library
import matplotlib.pyplot as plt

# CEA configuration and file locator
import cea.config
import cea.inputlocator


def read_manual_dtn(existing_dtn_filepath):
    """
    Option 1: Reads a user-defined CSV file that lists IDs of buildings connected to existing DTN.
    Returns a list of building IDs.
    """
    if existing_dtn_filepath and os.path.exists(existing_dtn_filepath):
        dtn_df = pd.read_csv(existing_dtn_filepath)
        return dtn_df['name'].tolist()
    else:
        return []


def read_automatic_dtn(locator, network_type='DH'):
    """
    Option 2: Automatically identify existing DN buildings using the nodes shapefile
    generated by the Thermal Network Part 1: Layout.
    The nodes shapefiles have a column named "building" where non-"NONE" values indicate
    buildings in the existing DN.
    """
    nodes_shp = gpd.read_file(locator.get_network_layout_nodes_shapefile(network_type, ""))
    # Filter nodes where the 'building' field is not "NONE"
    dtn_buildings = nodes_shp[nodes_shp['building'] != "NONE"]['building'].unique().tolist()
    # Return as a list of strings (ensure type)
    return [str(b) for b in dtn_buildings if b is not None]


def merge_building_data(buildings_shp, demand_df):
    """
    Merge building spatial data (from zone shapefile) with demand data (from Total_demand.csv).

    - Makes sure both inputs have the "name" field as string.
    - Calculates each building's centroid and extracts the x and y coordinates.

    Returns:
      A merged DataFrame containing building footprints, demand data, and centroid coordinates.
    """
    buildings_shp['name'] = buildings_shp['name'].astype(str)
    demand_df['name'] = demand_df['name'].astype(str)
    merged_df = buildings_shp.merge(demand_df, on='name', how='inner')
    merged_df['centroid'] = merged_df.geometry.centroid
    merged_df['x'] = merged_df['centroid'].apply(lambda pt: pt.x)
    merged_df['y'] = merged_df['centroid'].apply(lambda pt: pt.y)
    return merged_df


def prepare_features(merged_df, heat_col='QH_sys_MWhyr'):
    """
    Prepares the feature matrix for clustering:

    - Converts the annual heat demand from MWh/yr to kWh/yr (multiplication by 1000).
    - Selects the "heat_kWhyr" alongside the x and y coordinates.
    - Normalizes the features using StandardScaler.

    Returns:
      - scaled_features: a NumPy array with zero mean and unit variance.
      - scaler: the StandardScaler object (in case you need to reverse-transform).
    """
    merged_df['heat_kWhyr'] = merged_df[heat_col] * 1000
    features = merged_df[['heat_kWhyr', 'x', 'y']].copy()
    scaler = StandardScaler()
    scaled_features = scaler.fit_transform(features)
    return scaled_features, scaler


def perform_clustering(scaled_features, n_clusters):
    """
    Runs KMeans clustering on the standardized feature set.

    Parameters:
      - scaled_features: The normalized array of features (heat demand, x, y).
      - n_clusters: Number of clusters for the non-DTN buildings.

    Key Points:
      - random_state is set to 42 to guarantee reproducible results.
      - KMeans clusters the data into n_clusters by minimizing the within-cluster sum of squares.

    Returns:
      The cluster labels and the fitted KMeans model.
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(scaled_features)
    labels = kmeans.labels_
    return labels, kmeans


def save_results(merged_df, locator, output_name='building_clusters'):
    """
    Saves the results using CEA-compliant locator methods.
    """
    # Use locator methods defined in schemas.yml
    out_csv = locator.get_building_clusters()
    merged_df.to_csv(out_csv, index=False)
    
    out_shp = locator.get_building_clusters_shapefile()
    merged_df.to_file(out_shp, driver="ESRI Shapefile")
    
    return out_csv, out_shp



def visualize_clusters(merged_df):
    """
    Visualizes the clustered buildings using a scatter plot of centroids.
    """
    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(merged_df['x'], merged_df['y'], c=merged_df['cluster'],
                          cmap='viridis', s=50, edgecolor='k')
    plt.xlabel('X Coordinate')
    plt.ylabel('Y Coordinate')
    plt.title('Building Clusters based on Thermal Demand and Proximity')
    plt.colorbar(scatter, label='Cluster Label')
    plt.show()


def cluster_buildings(buildings_shp, demand_df, locator,
                      dtn_method='automatic',
                      existing_dtn_filepath=None,
                      extra_clusters=2, network_type='DH'):
    """
    Main clustering function.

    The DTN selection can be done in two ways:
      - "automatic": Reads the network nodes shapefile to get buildings with non-"NONE" building.
                     Currently only for DH networks.
      - "manual": Reads a user-specified CSV file (existing_dtn_filepath).

    Buildings in the DTN are assigned a cluster label 0.
    Buildings not in the DTN are clustered into extra_clusters (minimum 2),
    and their labels are shifted by +1.
    """
    # Merge spatial data and demand data.
    merged_df = merge_building_data(buildings_shp, demand_df)

    # Identify DTN buildings.
    if dtn_method == 'automatic':
        dtn_buildings = read_automatic_dtn(locator, network_type)
    elif dtn_method == 'manual':
        dtn_buildings = read_manual_dtn(existing_dtn_filepath)
    else:
        dtn_buildings = []

    print("DTN Buildings:", dtn_buildings)

    # Add a flag to mark DTN buildings.
    merged_df['in_existing_DTN'] = merged_df['name'].isin(dtn_buildings)

    # Separate DTN and non-DTN buildings.
    dtn_df = merged_df[merged_df['in_existing_DTN']].copy()
    non_dtn_df = merged_df[~merged_df['in_existing_DTN']].copy()

    # For non-DTN buildings, prepare features and perform clustering.
    scaled_features, scaler = prepare_features(non_dtn_df, heat_col='QH_sys_MWhyr')
    extra_clusters = max(2, extra_clusters)
    labels, kmeans = perform_clustering(scaled_features, n_clusters=extra_clusters)
    non_dtn_df['cluster'] = labels + 1  # Shift labels so that DTN becomes cluster 0.

    # For DTN buildings, assign a cluster label of 0.
    if not dtn_df.empty:
        dtn_df['cluster'] = 0
        final_df = pd.concat([dtn_df, non_dtn_df], ignore_index=True)
    else:
        final_df = non_dtn_df

    # Save results and visualize.
    out_csv, out_shp = save_results(final_df, locator, output_name='building_clusters')
    print(f"Results saved to:\nCSV: {out_csv}\nShapefile: {out_shp}")
    visualize_clusters(final_df)


def main(config):
    """
    Main function to run the building clustering.

    Inputs:
      - Uses the scenario folder specified by config.
      - Loads the zone shapefile (building footprints).
      - Loads Total_demand.csv for thermal demand (using QH_sys_MWhyr).
      - DTN selection method can be specified:
          * dtn_method = 'automatic'  OR  'manual'
      - For manual, set existing_dtn_filepath to a CSV file path.
      - extra_clusters: number of extra clusters to generate for non-DTN buildings.
      - network_type: typically 'DH' for district heating (or 'DC' for cooling).

    Outputs:
      - Saves clustered building data to CSV and shapefile.
      - Visualizes the clusters.
    """
    if not os.path.exists(config.scenario):
        raise FileNotFoundError(f"Scenario not found: {config.scenario}")

    locator = cea.inputlocator.InputLocator(scenario=config.scenario)
    buildings_shp = gpd.read_file(locator.get_zone_geometry())
    demand_df = pd.read_csv(locator.get_total_demand())

    # --- DTN Selection ---
    # Specify DTN method: use 'automatic' to read from network nodes shapefile,
    # or 'manual' to provide a CSV file.
    dtn_method = 'automatic'
    existing_dtn_filepath = None  # For manual selection, e.g., "inputs/dtn_selection.csv"

    # Specify extra clusters for non-DTN buildings.
    extra_clusters = 3
    network_type = 'DH'  # or 'DC'

    cluster_buildings(buildings_shp, demand_df, locator,
                      dtn_method=dtn_method,
                      existing_dtn_filepath=existing_dtn_filepath,
                      extra_clusters=extra_clusters,
                      network_type=network_type)


if __name__ == '__main__':
    main(cea.config.Configuration())
