#!/usr/bin/env python3
"""
DTN_expansion_optimization.py
=============================
A workflow to stage the expansion of an existing (cluster‑0) District Thermal
Network (DTN) into an arbitrary number of *phases* while maximizing a financial
objective (ROI, NPV or simple pay‑back).

Key design philosophy
---------------------
* **Single network layout** – we reuse the *Part 1* master layout that connects
  **all** candidate buildings.  This avoids having to regenerate geometry for
  each phase and ensures pipe positions & diameters stay consistent.
* **Edge activation** – every pipe (edge) in that master graph carries a
  Boolean `active` flag.  When a cluster is assigned to a phase we activate the
  path that links its nodes to the already‑active network.  CAPEX is charged
  *only once* per edge – the phase that first activates it.
* **Modular optimization layer** – the cost / hydraulic model is kept strictly
  separate from the search algorithm.  You may plug‑in Greedy, A*, Genetic
  Algorithm, etc. simply by switching the `choose_next_phase()` strategy.
* **CEA integration ready** – inputs are read via `cea.inputlocator.InputLocator`
  and parameters via `cea.config.Configuration`.  The script therefore runs
  seamlessly from the CEA CLI or Dashboard once registered in `scripts.yml`.
  --------------------
 **REV 6 – _node / edge clustering only_**

This revision does **one thing only**: it maps every *node* and *edge* of an
existing Part‑1 network layout to the building–clusters generated by
`building_clustering.py` and stores the result as CSV.  No phasing, no CAPEX
math yet – those will follow in later revisions once this data layer is rock
solid.

Output files written to
`{scenario}/outputs/data/optimization/dtn_expansion/`  ▸

* `cluster_nodes.csv` → one row per node, with its cluster id and role
  (CONSUMER / PLANT / OTHER)
* `cluster_edges.csv` → one row per edge, with:
    * `edge_id` (taken from `edges.shp` *Name* attribute if present, or a
      synthetic id)
    * `cluster_src` / `cluster_dst` – cluster of each incident node
    * `intra_cluster` (1 if src==dst)
      └─ those edges are considered “owned” by that cluster
    * length [m], diameter [mm], material, etc. (copied verbatim from shp)

These two CSVs form the basis for any later CAPEX or phasing logic.
"""
from __future__ import annotations

###############################################################################
# 1) STANDARD IMPORTS                                                        #
###############################################################################
import argparse
import logging
import time
import itertools
import random
from pathlib import Path
from typing import Dict, Tuple, List, Set, Optional, Union

import geopandas as gpd
import pandas as pd
import numpy as np
import networkx as nx
from deap import base, tools, algorithms, creator

# Create the Individual class
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

import cea.config               # type: ignore
import cea.inputlocator         # type: ignore
from cea.constants import HEAT_CAPACITY_OF_WATER_JPERKGK
from cea.analysis.costs.equations import calc_capex_annualized

###############################################################################
# 2) LOGGING                                                                 #
###############################################################################

def log()->logging.Logger:
    lg = logging.getLogger("cea.dtn_expansion")
    if not lg.handlers:
        logging.basicConfig(level=logging.INFO,
                            format="%(asctime)s | %(levelname)5s | %(message)s",
                            datefmt="%H:%M:%S")
    return lg

###############################################################################
# 3) HELPERS                                                                 #
###############################################################################

def _read_shp_force_2d(path: Path) -> gpd.GeoDataFrame:
    """Load shapefile and drop Z‑coords that sometimes sneak in."""
    gdf = gpd.read_file(path)
    if gdf.geometry.iloc[0].has_z:
        gdf["geometry"] = gdf.geometry.apply(lambda g: type(g)([(x, y) for x, y, *_ in g.coords]))
    return gdf

###############################################################################
# 4) CORE SCRIPT                                                             #
###############################################################################

class ClusterMapper:
    """Map nodes / edges ➜ cluster ids using Edge‑Node incidence matrix."""

    def __init__(self, locator: cea.inputlocator.InputLocator, net_type: str):
        self.loc = locator
        self.net_type = net_type
        self._load_inputs()
        self._build_lookup()

    def _load_inputs(self):
        # 1) building cluster assignments
        path_cl = Path(self.loc.get_dtn_cluster_assignment_file())
        self.df_clusters = pd.read_csv(path_cl)
        log().info("Building clusters loaded: %d rows", len(self.df_clusters))
        # 2) Part‑1 network layout shapefiles
        nodes_shp = Path(self.loc.get_network_layout_nodes_shapefile(self.net_type))
        edges_shp = nodes_shp.with_name("edges.shp")
        self.gdf_nodes = _read_shp_force_2d(nodes_shp)
        self.gdf_edges = _read_shp_force_2d(edges_shp)
        log().info("Network layout loaded: %d nodes, %d edges", len(self.gdf_nodes), len(self.gdf_edges))
        # 3) edge–node incidence CSV
        inc_path = Path(self.loc.scenario) / "outputs" / "data" / "thermal-network" / f"{self.net_type}__EdgeNode.csv"
        self.df_inc = pd.read_csv(inc_path, index_col=0)
        log().info("Edge–Node incidence matrix: %d nodes × %d edges", *self.df_inc.shape)

    def _build_lookup(self):
        # map building name -> cluster id
        b2c = dict(self.df_clusters[["name","cluster"]].values)
        # assign cluster to nodes
        clusters = []
        for _, row in self.gdf_nodes.iterrows():
            typ = row.get("type","").upper()
            if typ == "CONSUMER":
                bld = row.get("building")
                clusters.append(b2c.get(str(bld), -1))
            elif typ == "PLANT":
                clusters.append(0)
            else:
                clusters.append(-1)
        self.gdf_nodes["cluster"] = clusters
        # assign cluster_src/dst to edges via incidence
        src_list, dst_list = [], []
        for eid in self.df_inc.columns:
            vec = self.df_inc[eid]
            nodes = [n for n,v in vec.items() if v != 0]
            if len(nodes) != 2:
                src_list.append(-1); dst_list.append(-1)
                continue
            n1,n2 = nodes
            c1 = int(self.gdf_nodes.loc[self.gdf_nodes["name"]==n1, "cluster"].iloc[0])
            c2 = int(self.gdf_nodes.loc[self.gdf_nodes["name"]==n2, "cluster"].iloc[0])
            src_list.append(c1); dst_list.append(c2)
        self.gdf_edges["cluster_src"] = src_list
        self.gdf_edges["cluster_dst"] = dst_list

    def write_outputs(self):
        out_folder = Path(self.loc.get_dtn_expansion_optimization_results_folder())
        out_folder.mkdir(parents=True, exist_ok=True)

        # --- update node shapefile with cluster and save
        # Rearrange columns in nodes_clustered shapefiles as per requirement iii)
        nodes_out_shp = out_folder / "nodes_clustered.shp"
        # Ensure columns are in the specified order: 'name', 'type', 'building', 'cluster'
        node_columns = ["name", "type", "building", "cluster"]
        # Add any other columns that might be in the dataframe
        for col in self.gdf_nodes.columns:
            if col not in node_columns and col != "geometry":
                node_columns.append(col)
        # Add geometry at the end
        if "geometry" in self.gdf_nodes.columns:
            node_columns.append("geometry")

        # Reorder columns and save
        self.gdf_nodes = self.gdf_nodes[node_columns]
        self.gdf_nodes.to_file(nodes_out_shp)
        log().info("Wrote clustered nodes shapefile → %s", nodes_out_shp)

        # --- write cluster_nodes.csv
        nodes_csv = out_folder / "cluster_nodes.csv"
        self.gdf_nodes[["name", "type", "building", "cluster"]].to_csv(nodes_csv, index=False)
        log().info("Wrote cluster_nodes.csv → %s", nodes_csv)

        # --- update edge shapefile with new cluster fields and save
        # Rename columns as per requirement i)
        self.gdf_edges = self.gdf_edges.rename(columns={
            "cluster_src": "from_C",
            "cluster_dst": "to_C"
        })

        # Add cluster column to edges_clustered shapefile
        def pick_cluster(r):
            if r["from_C"] != r["to_C"] and r["from_C"] != -1 and r["to_C"] != -1:
                return -1  # Inter-cluster edge
            if r["from_C"] == -1:
                return r["to_C"]
            return r["from_C"]

        self.gdf_edges["cluster"] = self.gdf_edges.apply(pick_cluster, axis=1)

        # Save the updated edges shapefile
        edges_out_shp = out_folder / "edges_clustered.shp"
        self.gdf_edges.to_file(edges_out_shp)
        log().info("Wrote clustered edges shapefile → %s", edges_out_shp)

        # --- prepare cluster_edges.csv as per requirement ii)
        df = self.gdf_edges.copy()

        # Ensure we have the required columns
        if "Name" in df.columns:
            df["name"] = df["Name"]
        elif "edge_id" in df.columns:
            df["name"] = df["edge_id"]
        else:
            df = df.reset_index()
            df["name"] = df["index"].astype(str)

        # Add length_m column if it exists with a different name
        if "length_m" not in df.columns and "LENGTH" in df.columns:
            df["length_m"] = df["LENGTH"]
        elif "length_m" not in df.columns and "Length" in df.columns:
            df["length_m"] = df["Length"]

        # Add pipe_DN column if it exists with a different name
        if "pipe_DN" not in df.columns and "D_int_m" in df.columns:
            # Convert from meters to mm and round to nearest standard DN size
            df["pipe_DN"] = (df["D_int_m"] * 1000).round().astype(int)

        # Add type_mat column if it exists with a different name
        if "type_mat" not in df.columns and "material" in df.columns:
            df["type_mat"] = df["material"]

        # Select and order columns as required
        cols = ["name", "length_m", "pipe_DN", "type_mat", "from_C", "to_C", "cluster"]

        # Ensure all required columns exist (create empty ones if needed)
        for col in cols:
            if col not in df.columns:
                df[col] = ""

        edges_csv = out_folder / "cluster_edges.csv"
        df[cols].to_csv(edges_csv, index=False)
        log().info("Wrote cluster_edges.csv → %s", edges_csv)

# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Assign network nodes/edges to building clusters")
    p.add_argument("scenario", help="CEA scenario root folder")
    p.add_argument("--network-type", choices=["DH","DC"], default="DH")
    p.add_argument("--chosen-clusters", help="Comma-separated list of cluster IDs to include (e.g., '1,3,4')")
    p.add_argument("--chosen-buildings", help="Comma-separated list of building names to include")
    return p.parse_args()


def check_thermal_network_prerequisites(locator, network_type, bypass_check=False):
    """
    Check if the required thermal network files exist.

    Parameters:
    -----------
    locator : InputLocator
        CEA InputLocator object
    network_type : str
        'DH' for district heating or 'DC' for district cooling
    bypass_check : bool
        If True, bypass the prerequisite check (useful for testing with a subset of buildings)

    Returns:
    --------
    bool
        True if all prerequisites are met or bypass_check is True, False otherwise
    """
    if bypass_check:
        log().warning("Bypassing thermal network prerequisites check. Make sure you have the necessary files for your chosen buildings.")
        return True

    # Check for Part 1 (layout) files
    try:
        edge_node_file = Path(locator.get_thermal_network_edge_node_matrix_file(network_type))
        if not edge_node_file.exists():
            log().error(f"Thermal Network Part 1 (layout) files not found. Please run Thermal Network Part 1 first.")
            return False

        # Check for Part 2 (simulation) files
        plant_heat_file = Path(locator.get_thermal_network_plant_heat_requirement_file(network_type, ""))
        if not plant_heat_file.exists():
            log().error(f"Thermal Network Part 2 (simulation) files not found. Please run Thermal Network Part 2 with detailed model first.")
            return False

        # Check for Part 3 (costs) files
        costs_file = Path(locator.get_network_layout_costs_file(network_type))
        if not costs_file.exists():
            log().error(f"Thermal Network Part 3 (costs) files not found. Please run Thermal Network Part 3 first.")
            return False

        # Check for Total_demand.csv
        total_demand_file = Path(locator.get_total_demand())
        if not total_demand_file.exists():
            log().error(f"Total demand file not found. Please run the demand script first.")
            return False

        return True
    except Exception as e:
        log().error(f"Error checking prerequisites: {str(e)}")
        return False

class DTNExpansionOptimizer:
    """
    Optimize the phased expansion of district thermal networks using genetic algorithm.

    This class assigns clusters to different phases to maximize overall ROI while
    respecting budget constraints for each phase.
    """

    def __init__(self, locator: cea.inputlocator.InputLocator, network_type: str, 
                 metrics_df: pd.DataFrame, num_phases: int = 3, 
                 budget_per_phase: Optional[List[float]] = None, 
                 energy_price: float = 0.1, interest_rate: float = 0.05,
                 cost_model: str = 'detailed'):
        """
        Initialize the DTN expansion optimizer.

        Parameters:
        -----------
        locator : cea.inputlocator.InputLocator
            CEA InputLocator object
        network_type : str
            'DH' for district heating or 'DC' for district cooling
        metrics_df : pd.DataFrame
            DataFrame with metrics for all cluster combinations
        num_phases : int
            Number of phases for the expansion
        budget_per_phase : list, optional
            Budget available for each phase (in USD)
        energy_price : float
            Energy price for calculating revenue (USD/kWh)
        interest_rate : float
            Annual interest rate for NPV calculations
        cost_model : str
            Method for calculating pipe costs ('simplified' or 'detailed')
        """
        self.locator = locator
        self.network_type = network_type
        self.metrics_df = metrics_df
        self.num_phases = num_phases
        self.budget_per_phase = budget_per_phase or [float('inf')] * num_phases
        self.energy_price = energy_price
        self.interest_rate = interest_rate
        self.cost_model = cost_model

        # Load cost data from TN part 3 results
        self.cost_data = self._load_cost_data()

        # Load cluster data
        self._load_cluster_data()

        # Create a mapping from cluster combinations to their metrics
        self.cluster_metrics = self._create_cluster_metrics_mapping()

        # Initialize DEAP toolbox
        self.toolbox = base.Toolbox()
        self._setup_genetic_algorithm()

    def _load_cost_data(self):
        """Load cost data from thermal network costs results."""
        cost_file = Path(self.locator.get_network_layout_costs_file(self.network_type))
        if not cost_file.exists():
            raise FileNotFoundError(f"Cost file not found: {cost_file}. Please run Thermal Network Part 3 first.")

        cost_data = pd.read_csv(cost_file)

        # Extract relevant cost components
        cost_components = {
            'capex_network_USD': cost_data['capex_network_USD'].iloc[0],
            'capex_pumps_USD': cost_data['capex_pumps_USD'].iloc[0],
            'capex_hex_USD': cost_data['capex_hex_USD'].iloc[0],
            'network_length_m': cost_data['network_length_m'].iloc[0],
        }

        # Calculate cost per meter of pipe (for simplified model)
        cost_components['cost_per_meter'] = cost_components['capex_network_USD'] / cost_components['network_length_m']

        return cost_components

    def _load_cluster_data(self):
        """Load cluster data from cluster_edges.csv and cluster_nodes.csv."""
        # Load cluster assignments
        cluster_edges_path = Path(self.locator.get_dtn_expansion_optimization_results_folder()) / "cluster_edges.csv"
        self.cluster_edges = pd.read_csv(cluster_edges_path)

        cluster_nodes_path = Path(self.locator.get_dtn_expansion_optimization_results_folder()) / "cluster_nodes.csv"
        self.cluster_nodes = pd.read_csv(cluster_nodes_path)

        # Load total demand
        total_demand_path = Path(self.locator.get_total_demand())
        self.total_demand = pd.read_csv(total_demand_path)

        # Extract unique clusters from the metrics DataFrame
        # This ensures we only consider clusters that have metrics (i.e., the chosen clusters)
        unique_clusters = set()
        for cluster_str in self.metrics_df['clusters']:
            # Skip cluster 0 (existing DTN)
            if cluster_str == '0':
                continue
            # Split the cluster string (e.g., '1+3+4') into individual clusters
            for c in cluster_str.split('+'):
                if c != '0':  # Skip cluster 0
                    unique_clusters.add(int(c))

        # Sort the clusters to maintain the same order as before
        self.all_clusters = sorted(list(unique_clusters))

        log().info(f"Using {len(self.all_clusters)} clusters from metrics: {self.all_clusters}")

        # Get total number of buildings
        self.total_buildings = len(self.total_demand['name'].unique())

    def _create_cluster_metrics_mapping(self):
        """Create a mapping from cluster combinations to their metrics."""
        cluster_metrics = {}
        for _, row in self.metrics_df.iterrows():
            cluster_metrics[row['clusters']] = row.to_dict()
        return cluster_metrics

    def get_required_pipes_for_clusters(self, cluster_set):
        """
        Determine the minimum required pipes for a set of clusters.

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs to connect

        Returns:
        --------
        pd.DataFrame
            DataFrame of required pipes
        """
        # Include cluster 0 (existing DTN) in the set
        clusters_to_connect = set(cluster_set).union({0})

        # Get edges that belong to the clusters in the set
        cluster_edges = self.cluster_edges[self.cluster_edges['cluster'].isin(clusters_to_connect)]

        # Get main road edges (-1) that connect the clusters
        main_road_edges = self.cluster_edges[
            (self.cluster_edges['cluster'] == -1) & 
            (self.cluster_edges['from_C'].isin(clusters_to_connect)) & 
            (self.cluster_edges['to_C'].isin(clusters_to_connect))
        ]

        # Combine the edges
        required_pipes = pd.concat([cluster_edges, main_road_edges])

        return required_pipes

    def _get_buildings_in_clusters(self, cluster_set):
        """
        Get all buildings in the specified clusters.

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs

        Returns:
        --------
        list
            List of building names
        """
        # Include cluster 0 (existing DTN) in the set
        clusters_to_connect = set(cluster_set).union({0})

        # Get buildings in the clusters
        buildings = self.cluster_nodes[
            (self.cluster_nodes['cluster'].isin(clusters_to_connect)) & 
            (self.cluster_nodes['type'] == 'CONSUMER')
        ]['building'].tolist()

        return buildings

    def _get_buildings_in_specific_cluster(self, cluster_id):
        """
        Get buildings in a specific cluster only.

        Parameters:
        -----------
        cluster_id : int
            Cluster ID

        Returns:
        --------
        list
            List of building names in the specific cluster
        """
        # Get buildings in the specific cluster
        buildings = self.cluster_nodes[
            (self.cluster_nodes['cluster'] == cluster_id) & 
            (self.cluster_nodes['type'] == 'CONSUMER')
        ]['building'].tolist()

        return buildings

    def calculate_detailed_capex(self, cluster_set):
        """
        Calculate CAPEX using detailed pipe diameter information.

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs

        Returns:
        --------
        float
            Total pipe CAPEX
        """
        # Get edges for this cluster set
        required_pipes = self.get_required_pipes_for_clusters(cluster_set)

        # Load pipe cost data
        piping_cost_data = pd.read_csv(self.locator.get_database_components_distribution_thermal_grid('THERMAL_GRID'))

        # Merge with cost data
        cost_df = required_pipes.merge(piping_cost_data, on='pipe_DN')

        # Calculate cost for each pipe segment
        cost_df['pipe_cost'] = cost_df['Inv_USD2015perm'] * cost_df['length_m']

        # Sum up all pipe costs
        total_pipe_cost = cost_df['pipe_cost'].sum()

        return total_pipe_cost

    def calculate_simplified_capex(self, cluster_set):
        """
        Calculate CAPEX using simplified average cost per meter.

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs

        Returns:
        --------
        float
            Total pipe CAPEX
        """
        # Get edges for this cluster set
        required_pipes = self.get_required_pipes_for_clusters(cluster_set)

        # Calculate total pipe length
        total_pipe_length = required_pipes['length_m'].sum()

        # Calculate cost using average cost per meter
        total_pipe_cost = total_pipe_length * self.cost_data['cost_per_meter']

        return total_pipe_cost

    def _calculate_phase_capex(self, cluster_set):
        """
        Calculate total CAPEX for a phase.

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs

        Returns:
        --------
        float
            Total CAPEX for the phase
        """
        # Calculate pipe CAPEX based on selected cost model
        if self.cost_model == 'detailed':
            pipe_capex = self.calculate_detailed_capex(cluster_set)
        else:
            pipe_capex = self.calculate_simplified_capex(cluster_set)

        # Get buildings in the clusters
        buildings = self._get_buildings_in_clusters(cluster_set)

        # Calculate heat exchanger costs based on number of buildings
        hex_capex = len(buildings) * (self.cost_data['capex_hex_USD'] / self.total_buildings)

        # Calculate pump costs based on pipe length ratio
        required_pipes = self.get_required_pipes_for_clusters(cluster_set)
        pipe_length_ratio = required_pipes['length_m'].sum() / self.cost_data['network_length_m']
        pump_capex = self.cost_data['capex_pumps_USD'] * pipe_length_ratio

        # Calculate total CAPEX
        total_capex = pipe_capex + hex_capex + pump_capex

        return total_capex

    def calculate_roi(self, cluster_set, phase):
        """
        Calculate ROI for a cluster set in a specific phase.

        ROI = net annual return / CAPEX

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs
        phase : int
            Phase number (1-based)

        Returns:
        --------
        float
            Return on Investment (ROI)
        """
        # Get metrics for this cluster set
        key = '+'.join(map(str, sorted(cluster_set)))
        if key not in self.cluster_metrics:
            return -float('inf')  # Invalid cluster set

        metrics = self.cluster_metrics[key]

        # Calculate CAPEX
        capex = self._calculate_phase_capex(cluster_set)

        # Calculate annual revenue (energy price * annual demand)
        if self.network_type == 'DH':
            annual_demand_kwh = metrics['total_annual_Qh_MWh'] * 1000  # Convert MWh to kWh
        else:
            annual_demand_kwh = metrics['total_annual_Qc_MWh'] * 1000  # Convert MWh to kWh

        annual_revenue = annual_demand_kwh * self.energy_price

        # Calculate annual O&M costs (typically 2-3% of CAPEX)
        annual_om_cost = 0.025 * capex

        # Net annual return
        net_annual_return = annual_revenue - annual_om_cost

        # Calculate ROI (net annual return / CAPEX)
        if capex > 0:
            roi = net_annual_return / capex
        else:
            roi = 0

        return roi

    def calculate_npv(self, cluster_set, phase, years=20):
        """
        Calculate Net Present Value for a cluster set in a specific phase.

        Parameters:
        -----------
        cluster_set : tuple or list
            Tuple or list of cluster IDs
        phase : int
            Phase number (1-based)
        years : int
            Number of years for NPV calculation

        Returns:
        --------
        float
            Net Present Value (NPV)
        """
        # Get metrics for this cluster set
        key = '+'.join(map(str, sorted(cluster_set)))
        if key not in self.cluster_metrics:
            return -float('inf')  # Invalid cluster set

        metrics = self.cluster_metrics[key]

        # Calculate CAPEX
        capex = self._calculate_phase_capex(cluster_set)

        # Calculate annual revenue and O&M costs
        if self.network_type == 'DH':
            annual_demand_kwh = metrics['total_annual_Qh_MWh'] * 1000  # Convert MWh to kWh
        else:
            annual_demand_kwh = metrics['total_annual_Qc_MWh'] * 1000  # Convert MWh to kWh

        annual_revenue = annual_demand_kwh * self.energy_price
        annual_om_cost = 0.025 * capex
        net_annual_return = annual_revenue - annual_om_cost

        # Apply discount factor based on phase
        phase_year = phase - 1  # Phase 1 starts at year 0

        # Calculate NPV
        npv = -capex  # Initial investment (negative)
        for year in range(years):
            # Only start counting returns after the phase year
            if year >= phase_year:
                discount_factor = 1 / ((1 + self.interest_rate) ** (year + 1))
                npv += net_annual_return * discount_factor

        return npv

    def _setup_genetic_algorithm(self):
        """Set up the genetic algorithm using DEAP."""
        # Define genome representation: each gene is a phase number (1 to num_phases)
        # for each cluster (all clusters will be connected)
        self.toolbox.register("attr_phase", random.randint, 1, self.num_phases)
        self.toolbox.register("individual", tools.initRepeat, creator.Individual, 
                             self.toolbox.attr_phase, n=len(self.all_clusters))
        self.toolbox.register("population", tools.initRepeat, list, self.toolbox.individual)

        # Register genetic operators
        self.toolbox.register("evaluate", self._evaluate_individual)
        self.toolbox.register("mate", tools.cxTwoPoint)
        self.toolbox.register("mutate", tools.mutUniformInt, low=1, up=self.num_phases, indpb=0.2)
        self.toolbox.register("select", tools.selTournament, tournsize=3)

        # Register the map function (use the built-in map function)
        self.toolbox.register("map", map)

    def _evaluate_individual(self, individual):
        """
        Evaluate the fitness of an individual.

        Parameters:
        -----------
        individual : list
            List of phase assignments for each cluster

        Returns:
        --------
        tuple
            Fitness value (overall ROI)
        """
        # Convert individual to cluster-phase mapping
        cluster_phase_map = {cluster: phase for cluster, phase in zip(self.all_clusters, individual)}

        # Calculate total ROI across all phases
        total_roi = 0
        total_npv = 0

        # Check if budget constraints are satisfied
        phase_costs = [0] * self.num_phases

        # Group clusters by phase
        clusters_by_phase = {}
        for cluster, phase in cluster_phase_map.items():
            if phase > 0:  # Skip unconnected clusters (phase 0)
                if phase not in clusters_by_phase:
                    clusters_by_phase[phase] = []
                clusters_by_phase[phase].append(cluster)

        # Calculate ROI and costs for each phase
        for phase, clusters in clusters_by_phase.items():
            # Calculate CAPEX for this phase
            capex = self._calculate_phase_capex(clusters)
            phase_costs[phase-1] = capex

            # Calculate ROI for this phase
            roi = self.calculate_roi(tuple(clusters), phase)
            npv = self.calculate_npv(tuple(clusters), phase)

            total_roi += roi
            total_npv += npv

        # Check budget constraints
        for phase in range(self.num_phases):
            if phase < len(phase_costs) and phase_costs[phase] > self.budget_per_phase[phase]:
                # Apply penalty for exceeding budget
                total_roi = -1000
                total_npv = -1000000
                break

        return (total_roi,)  # Return as tuple for DEAP

    def optimize(self, population_size=50, num_generations=30):
        """
        Run the genetic algorithm to find the optimal phase assignment.

        Parameters:
        -----------
        population_size : int
            Size of the population
        num_generations : int
            Number of generations

        Returns:
        --------
        dict
            Dictionary with the optimal solution
        """
        # Create initial population
        pop = self.toolbox.population(n=population_size)

        # Evaluate the individuals with an invalid fitness
        invalid_ind = [ind for ind in pop if not ind.fitness.valid]
        fitnesses = self.toolbox.map(self.toolbox.evaluate, invalid_ind)

        # Assign fitness values to individuals
        for ind, fit in zip(invalid_ind, fitnesses):
            ind.fitness.values = fit

        # Track the best individual
        hof = tools.HallOfFame(1)

        # Track statistics
        stats = tools.Statistics(lambda ind: ind.fitness.values)
        stats.register("avg", np.mean)
        stats.register("min", np.min)
        stats.register("max", np.max)

        # Run the genetic algorithm
        pop, logbook = algorithms.eaSimple(pop, self.toolbox, cxpb=0.5, mutpb=0.2, 
                                          ngen=num_generations, stats=stats, 
                                          halloffame=hof, verbose=True)

        # Get the best solution
        best_individual = hof[0]

        # Convert to cluster-phase mapping
        solution = {
            'cluster_phase_map': {cluster: phase for cluster, phase in 
                                 zip(self.all_clusters, best_individual) if phase > 0},
            'fitness': best_individual.fitness.values[0],
            'phases': {}
        }

        # Group clusters by phase
        for cluster, phase in solution['cluster_phase_map'].items():
            if phase not in solution['phases']:
                solution['phases'][phase] = []
            solution['phases'][phase].append(cluster)

        # Calculate metrics for each phase
        for phase, clusters in solution['phases'].items():
            solution[f'phase_{phase}_roi'] = self.calculate_roi(tuple(clusters), phase)
            solution[f'phase_{phase}_npv'] = self.calculate_npv(tuple(clusters), phase)
            solution[f'phase_{phase}_capex'] = self._calculate_phase_capex(clusters)

        return solution

    def save_results(self, solution):
        """
        Save optimization results to CSV.

        Parameters:
        -----------
        solution : dict
            Dictionary with the optimization solution
        """
        # Create output directory
        output_dir = Path(self.locator.get_dtn_expansion_optimization_results_folder())
        output_dir.mkdir(parents=True, exist_ok=True)

        # Create a DataFrame with the results
        results = []
        total_capex = 0
        total_npv = 0

        # Determine the network type and demand type
        if self.network_type == 'DH':
            demand_type = 'Qh'
        else:
            demand_type = 'Qc'

        # Track cumulative values
        cumulative_clusters = {0}  # Start with cluster 0 (existing DTN)
        cumulative_pipe_length = 0

        # Get buildings in cluster 0 (existing DTN)
        cluster0_buildings = self._get_buildings_in_specific_cluster(0)
        cumulative_buildings = set(cluster0_buildings)

        # Add a row for phase 0 (existing DTN)
        phase0_result = {
            'phase': 0,
            'newly_connected_cluster(s)': '0',
            'cumulative_cluster(s)': '0',
            'number_of_newly_connected_buildings': len(cluster0_buildings),
            'cumulative_number_of_buildings_connected': len(cluster0_buildings),
            'new_cluster(s)_roi [-]': 0,  # No ROI for existing DTN
            'new_cluster(s)_npv [USD]': 0,  # No NPV for existing DTN
            'new_cluster(s)_capex [USD]': 0,  # No CAPEX for existing DTN
            'new_cluster(s)_annual_revenue [USD/yr]': 0,  # No revenue for existing DTN in expansion calculation
            'new_cluster(s)_annual_om_cost [USD/yr]': 0,  # Will be calculated based on estimated CAPEX
            f'new_cluster(s)_annual_{demand_type} [MWh/yr]': 0,  # Will be calculated if data is available
            'new_cluster(s)_pipe_length [m]': 0,  # No new pipes for existing DTN
            'overall_roi [-]': 0,  # No overall ROI for phase 0
            'overall_npv [USD]': 0,  # No overall NPV for phase 0
            'overall_capex [USD]': 0,  # No overall CAPEX for phase 0
            'overall_annual_revenue [USD/yr]': 0,  # No overall revenue for phase 0
            'overall_annual_om_cost [USD/yr]': 0,  # No overall O&M cost for phase 0
            f'overall_annual_{demand_type} [MWh/yr]': 0,  # No overall annual demand for phase 0
            'cumulative_pipe_length [m]': 0,  # Will be updated if data is available
            f'newly_connected_linear_{demand_type}_density [MWh/km/yr]': 0,  # Will be calculated if data is available
            f'overall_linear_{demand_type}_density [MWh/km/yr]': 0,  # Will be calculated if data is available
            'budget [USD]': 0  # No budget for existing DTN
        }

        # Try to get metrics for cluster 0 if available
        cluster0_key = '0'
        if cluster0_key in self.cluster_metrics:
            metrics = self.cluster_metrics[cluster0_key]
            annual_demand = metrics.get(f'total_annual_{demand_type}_MWh', 0)
            pipe_length = metrics.get('total_pipe_length_m', 0)

            # Update phase 0 metrics
            phase0_result[f'new_cluster(s)_annual_{demand_type} [MWh/yr]'] = annual_demand
            phase0_result[f'overall_annual_{demand_type} [MWh/yr]'] = annual_demand
            phase0_result['cumulative_pipe_length [m]'] = pipe_length
            phase0_result[f'new_cluster(s)_linear_{demand_type}_density [MWh/km/yr]'] = metrics.get(f'linear_{demand_type}_density_MWh_per_km', 0)
            phase0_result[f'overall_linear_{demand_type}_density [MWh/km/yr]'] = metrics.get(f'linear_{demand_type}_density_MWh_per_km', 0)

            # Calculate annual revenue for cluster 0 (not counted in expansion ROI)
            annual_demand_kwh = annual_demand * 1000  # Convert MWh to kWh
            phase0_result['new_cluster(s)_annual_revenue [USD/yr]'] = annual_demand_kwh * self.energy_price
            phase0_result['overall_annual_revenue [USD/yr]'] = annual_demand_kwh * self.energy_price

            # Estimate CAPEX for cluster 0 (for O&M calculation only, not counted in expansion costs)
            estimated_capex = 0
            if self.cost_model == 'detailed':
                estimated_capex = self.calculate_detailed_capex((0,))
            else:
                estimated_capex = self.calculate_simplified_capex((0,))

            # Calculate O&M costs for cluster 0
            phase0_result['new_cluster(s)_annual_om_cost [USD/yr]'] = 0.025 * estimated_capex
            phase0_result['overall_annual_om_cost [USD/yr]'] = 0.025 * estimated_capex

            # Update cumulative pipe length
            cumulative_pipe_length = pipe_length

        results.append(phase0_result)

        # Calculate metrics for each phase
        for phase, clusters in sorted(solution['phases'].items()):
            # Get metrics for this cluster set
            key = '+'.join(map(str, sorted(clusters)))
            metrics = self.cluster_metrics.get(key, {})

            # Calculate financial metrics
            roi = solution[f'phase_{phase}_roi']
            npv = solution[f'phase_{phase}_npv']
            capex = solution[f'phase_{phase}_capex']

            # Calculate annual O&M costs (2.5% of CAPEX)
            annual_om_cost = 0.025 * capex

            # Calculate annual revenue
            annual_demand_kwh = metrics.get(f'total_annual_{demand_type}_MWh', 0) * 1000  # Convert MWh to kWh
            annual_revenue = annual_demand_kwh * self.energy_price

            # Get pipe length and linear heat density
            pipe_length = metrics.get('total_pipe_length_m', 0)
            linear_heat_density = metrics.get(f'linear_{demand_type}_density_MWh_per_km', 0)

            # Get buildings in each cluster individually
            newly_connected_buildings = set()
            for cluster in clusters:
                cluster_buildings = self._get_buildings_in_specific_cluster(cluster)
                newly_connected_buildings.update(cluster_buildings)

            num_newly_connected_buildings = len(newly_connected_buildings)

            # Update cumulative values
            cumulative_clusters.update(clusters)
            cumulative_pipe_length += pipe_length
            cumulative_buildings.update(newly_connected_buildings)

            # Calculate overall linear heat density for all connected clusters so far
            overall_annual_demand = sum(r[f'new_cluster(s)_annual_{demand_type} [MWh/yr]'] for r in results)
            overall_annual_demand += metrics.get(f'total_annual_{demand_type}_MWh', 0)
            overall_linear_density = overall_annual_demand / (cumulative_pipe_length / 1000) if cumulative_pipe_length > 0 else 0

            # Add to totals
            total_capex += capex
            total_npv += npv

            # Calculate cumulative values for overall columns
            # Sum up values from all previous phases including current phase
            overall_capex = sum(r.get('new_cluster(s)_capex [USD]', 0) for r in results) + capex
            overall_npv = sum(r.get('new_cluster(s)_npv [USD]', 0) for r in results) + npv
            overall_annual_revenue = sum(r.get('new_cluster(s)_annual_revenue [USD/yr]', 0) for r in results) + annual_revenue
            overall_annual_om_cost = sum(r.get('new_cluster(s)_annual_om_cost [USD/yr]', 0) for r in results) + annual_om_cost
            overall_annual_demand = sum(r.get(f'new_cluster(s)_annual_{demand_type} [MWh/yr]', 0) for r in results) + metrics.get(f'total_annual_{demand_type}_MWh', 0)

            # Calculate overall ROI (weighted by CAPEX)
            if overall_capex > 0:
                overall_roi = sum(r.get('new_cluster(s)_roi [-]', 0) * r.get('new_cluster(s)_capex [USD]', 0) for r in results if r['phase'] != 0)
                overall_roi = (overall_roi + (roi * capex)) / overall_capex
            else:
                overall_roi = 0

            # Create result dictionary with units
            # Note: All costs are in USD as per the internal calculations (e.g., Inv_USD2015perm, capex_hex_USD)
            result = {
                'phase': phase,
                'newly_connected_cluster(s)': '+'.join(map(str, sorted(clusters))),
                'cumulative_cluster(s)': '+'.join(map(str, sorted(cumulative_clusters))),
                'number_of_newly_connected_buildings': num_newly_connected_buildings,
                'cumulative_number_of_buildings_connected': len(cumulative_buildings),
                'new_cluster(s)_roi [-]': roi,
                'new_cluster(s)_npv [USD]': npv,
                'new_cluster(s)_capex [USD]': capex,
                'new_cluster(s)_annual_revenue [USD/yr]': annual_revenue,
                'new_cluster(s)_annual_om_cost [USD/yr]': annual_om_cost,
                f'new_cluster(s)_annual_{demand_type} [MWh/yr]': metrics.get(f'total_annual_{demand_type}_MWh', 0),
                'new_cluster(s)_pipe_length [m]': pipe_length,
                'overall_roi [-]': overall_roi,
                'overall_npv [USD]': overall_npv,
                'overall_capex [USD]': overall_capex,
                'overall_annual_revenue [USD/yr]': overall_annual_revenue,
                'overall_annual_om_cost [USD/yr]': overall_annual_om_cost,
                f'overall_annual_{demand_type} [MWh/yr]': overall_annual_demand,
                'cumulative_pipe_length [m]': cumulative_pipe_length,
                f'new_cluster(s)_linear_{demand_type}_density [MWh/km/yr]': linear_heat_density,
                f'overall_linear_{demand_type}_density [MWh/km/yr]': overall_linear_density,
                'budget [USD]': self.budget_per_phase[phase-1] if phase-1 < len(self.budget_per_phase) else 0
            }

            results.append(result)

        # Overall ROI is now calculated for each phase, so we don't need this calculation anymore
        # The final overall ROI is in the last phase's result
        if results and any(r['phase'] != 0 for r in results):
            last_phase_result = [r for r in results if r['phase'] != 0][-1]
            final_overall_roi = last_phase_result['overall_roi [-]']
        else:
            final_overall_roi = 0

        # Create DataFrame
        results_df = pd.DataFrame(results)

        # Add overall summary row
        summary = {
            'phase': 'Total',
            'newly_connected_cluster(s)': 'All',
            'cumulative_cluster(s)': '+'.join(map(str, sorted(cumulative_clusters))),
            'number_of_newly_connected_buildings': sum(result['number_of_newly_connected_buildings'] for result in results),
            'cumulative_number_of_buildings_connected': len(cumulative_buildings),
            'new_cluster(s)_roi [-]': sum(result['new_cluster(s)_roi [-]'] * result['new_cluster(s)_capex [USD]'] for result in results if result['phase'] != 0) / sum(result['new_cluster(s)_capex [USD]'] for result in results if result['phase'] != 0) if sum(result['new_cluster(s)_capex [USD]'] for result in results if result['phase'] != 0) > 0 else 0,
            'new_cluster(s)_npv [USD]': sum(result['new_cluster(s)_npv [USD]'] for result in results),
            'new_cluster(s)_capex [USD]': sum(result['new_cluster(s)_capex [USD]'] for result in results),
            'new_cluster(s)_annual_revenue [USD/yr]': sum(result['new_cluster(s)_annual_revenue [USD/yr]'] for result in results),
            'new_cluster(s)_annual_om_cost [USD/yr]': sum(result['new_cluster(s)_annual_om_cost [USD/yr]'] for result in results),
            f'new_cluster(s)_annual_{demand_type} [MWh/yr]': sum(result[f'new_cluster(s)_annual_{demand_type} [MWh/yr]'] for result in results),
            'new_cluster(s)_pipe_length [m]': sum(result.get('new_cluster(s)_pipe_length [m]', result.get('newly_added_pipe_length [m]', 0)) for result in results),
            'overall_roi [-]': final_overall_roi,
            'overall_npv [USD]': sum(result['new_cluster(s)_npv [USD]'] for result in results),
            'overall_capex [USD]': sum(result['new_cluster(s)_capex [USD]'] for result in results),
            'overall_annual_revenue [USD/yr]': sum(result['new_cluster(s)_annual_revenue [USD/yr]'] for result in results),
            'overall_annual_om_cost [USD/yr]': sum(result['new_cluster(s)_annual_om_cost [USD/yr]'] for result in results),
            f'overall_annual_{demand_type} [MWh/yr]': sum(result[f'new_cluster(s)_annual_{demand_type} [MWh/yr]'] for result in results),
            'cumulative_pipe_length [m]': cumulative_pipe_length,
            f'new_cluster(s)_linear_{demand_type}_density [MWh/km/yr]': 0,  # Average of all phases
            f'overall_linear_{demand_type}_density [MWh/km/yr]': 0,  # Will be calculated below
            'budget [USD]': sum(self.budget_per_phase)
        }

        # Calculate overall linear heat density
        if summary['cumulative_pipe_length [m]'] > 0:
            summary[f'overall_linear_{demand_type}_density [MWh/km/yr]'] = summary[f'overall_annual_{demand_type} [MWh/yr]'] / (summary['cumulative_pipe_length [m]'] / 1000)

        # Calculate average newly connected linear heat density (weighted by pipe length)
        total_pipe_length = sum(result.get('new_cluster(s)_pipe_length [m]', result.get('newly_added_pipe_length [m]', 0)) for result in results if result['phase'] != 0)
        if total_pipe_length > 0:
            summary[f'new_cluster(s)_linear_{demand_type}_density [MWh/km/yr]'] = sum(
                result.get(f'new_cluster(s)_linear_{demand_type}_density [MWh/km/yr]', result.get(f'newly_connected_linear_{demand_type}_density [MWh/km/yr]', 0)) * 
                result.get('new_cluster(s)_pipe_length [m]', result.get('newly_added_pipe_length [m]', 0)) 
                for result in results if result['phase'] != 0
            ) / total_pipe_length

        # Append summary row
        results_df = pd.concat([results_df, pd.DataFrame([summary])], ignore_index=True)

        # Add optimization settings as metadata
        metadata = {
            'network_type': self.network_type,
            'num_phases': self.num_phases,
            'cost_model': self.cost_model,
            'energy_price [USD/kWh]': self.energy_price,
            'interest_rate [-]': self.interest_rate,
            'budget_per_phase [USD]': ','.join(map(str, self.budget_per_phase))
        }

        # Save metadata to a separate CSV
        metadata_df = pd.DataFrame([metadata])
        metadata_file = output_dir / "optimization_settings.csv"
        metadata_df.to_csv(metadata_file, index=False)

        # Save results to CSV
        results_file = output_dir / "optimization_results.csv"
        results_df.to_csv(results_file, index=False)

        log().info(f"Optimization results saved to {results_file}")
        log().info(f"Optimization settings saved to {metadata_file}")

        return results_file

class PipeLayoutGenerator:
    """Generate pipe layouts for different sets of clusters and calculate metrics."""

    def __init__(self, locator: cea.inputlocator.InputLocator, network_type: str, phase: int = 1, chosen_clusters=None, chosen_buildings=None):
        """
        Initialize the PipeLayoutGenerator.

        Parameters:
        -----------
        locator : InputLocator
            CEA InputLocator object
        network_type : str
            'DH' for district heating or 'DC' for district cooling
        phase : int
            The phase number for the expansion
        chosen_clusters : list, optional
            List of cluster IDs to include (if None, all clusters are included)
        chosen_buildings : list, optional
            List of building names to include (if None, all buildings are included)
        """
        self.locator = locator
        self.network_type = network_type
        self.phase = phase
        self.chosen_clusters = chosen_clusters
        self.chosen_buildings = chosen_buildings
        self.output_folder = Path(locator.get_dtn_expansion_optimization_results_folder()) / f"phase_{phase}"
        self.output_folder.mkdir(parents=True, exist_ok=True)

        # Load input data
        self._load_inputs()

    def _load_inputs(self):
        """Load all necessary input data."""
        # Load cluster assignments
        cluster_edges_path = Path(self.locator.get_dtn_expansion_optimization_results_folder()) / "cluster_edges.csv"
        self.cluster_edges = pd.read_csv(cluster_edges_path)

        cluster_nodes_path = Path(self.locator.get_dtn_expansion_optimization_results_folder()) / "cluster_nodes.csv"
        self.cluster_nodes = pd.read_csv(cluster_nodes_path)

        # Load edge-node matrix
        edge_node_path = Path(self.locator.get_thermal_network_edge_node_matrix_file(self.network_type))
        self.edge_node_matrix = pd.read_csv(edge_node_path, index_col=0)

        # Load total demand
        total_demand_path = Path(self.locator.get_total_demand())
        self.total_demand = pd.read_csv(total_demand_path)

        # Filter by chosen buildings if specified
        if self.chosen_buildings:
            # Convert to list if it's a string
            if isinstance(self.chosen_buildings, str):
                self.chosen_buildings = [b.strip() for b in self.chosen_buildings.split(',') if b.strip()]

            log().info(f"Filtering to include only {len(self.chosen_buildings)} chosen buildings")

            # Get clusters that contain the chosen buildings
            building_clusters = self.cluster_nodes[
                (self.cluster_nodes['type'] == 'CONSUMER') & 
                (self.cluster_nodes['building'].isin(self.chosen_buildings))
            ]['cluster'].unique()

            # If chosen_clusters is not specified, use the clusters from chosen buildings
            if self.chosen_clusters is None:
                self.chosen_clusters = sorted([c for c in building_clusters if c > 0])
                log().info(f"Derived clusters from chosen buildings: {self.chosen_clusters}")

        # Get unique clusters (excluding 0 and -1)
        all_clusters = sorted([c for c in self.cluster_edges['cluster'].unique() if c > 0])

        # Filter by chosen clusters if specified
        if self.chosen_clusters:
            # Convert to list if it's a string
            if isinstance(self.chosen_clusters, str):
                self.chosen_clusters = [int(c.strip()) for c in self.chosen_clusters.split(',') if c.strip()]

            # Ensure all chosen clusters exist
            valid_clusters = [c for c in self.chosen_clusters if c in all_clusters]
            if len(valid_clusters) != len(self.chosen_clusters):
                missing = set(self.chosen_clusters) - set(valid_clusters)
                log().warning(f"Some chosen clusters do not exist: {missing}")

            self.clusters = sorted(valid_clusters)
            log().info(f"Using {len(self.clusters)} chosen clusters: {self.clusters}")
        else:
            self.clusters = all_clusters
            log().info(f"Using all {len(self.clusters)} clusters (excluding existing DTN and main roads)")

    def generate_all_cluster_combinations(self):
        """
        Generate all possible combinations of clusters.

        Returns:
        --------
        list
            List of all possible cluster combinations
        """
        all_combinations = []
        for r in range(1, len(self.clusters) + 1):
            combinations = list(itertools.combinations(self.clusters, r))
            all_combinations.extend(combinations)

        log().info(f"Generated {len(all_combinations)} possible cluster combinations")
        return all_combinations

    def get_required_pipes_for_clusters(self, cluster_set):
        """
        Determine the minimum required pipes for a set of clusters.

        Parameters:
        -----------
        cluster_set : tuple
            Tuple of cluster IDs to connect

        Returns:
        --------
        pd.DataFrame
            DataFrame of required pipes
        """
        # Include cluster 0 (existing DTN) in the set
        clusters_to_connect = set(cluster_set).union({0})

        # Get edges that belong to the clusters in the set
        cluster_edges = self.cluster_edges[self.cluster_edges['cluster'].isin(clusters_to_connect)]

        # Get main road edges (-1) that connect the clusters
        main_road_edges = self.cluster_edges[
            (self.cluster_edges['cluster'] == -1) & 
            (self.cluster_edges['from_C'].isin(clusters_to_connect)) & 
            (self.cluster_edges['to_C'].isin(clusters_to_connect))
        ]

        # Combine the edges
        required_pipes = pd.concat([cluster_edges, main_road_edges])

        return required_pipes

    def calculate_metrics(self, cluster_set, required_pipes):
        """
        Calculate metrics for a set of clusters.

        Parameters:
        -----------
        cluster_set : tuple
            Tuple of cluster IDs to connect
        required_pipes : pd.DataFrame
            DataFrame of required pipes

        Returns:
        --------
        dict
            Dictionary of metrics
        """
        # Include cluster 0 (existing DTN) in the set
        clusters_to_connect = set(cluster_set).union({0})

        # Calculate total pipe length
        total_pipe_length = required_pipes['length_m'].sum()

        # Get buildings in the clusters
        buildings_in_clusters = self.cluster_nodes[
            (self.cluster_nodes['cluster'].isin(clusters_to_connect)) & 
            (self.cluster_nodes['type'] == 'CONSUMER')
        ]['building'].tolist()

        # Calculate total annual demand
        if self.network_type == 'DH':
            # For district heating, use Qhs_sys_MWhyr
            total_annual_demand = self.total_demand[
                self.total_demand['name'].isin(buildings_in_clusters)
            ]['Qhs_sys_MWhyr'].sum()
            demand_type = 'Qh'
        else:
            # For district cooling, use Qcs_sys_MWhyr
            total_annual_demand = self.total_demand[
                self.total_demand['name'].isin(buildings_in_clusters)
            ]['Qcs_sys_MWhyr'].sum()
            demand_type = 'Qc'

        # Calculate linear heat density (LHD)
        if total_pipe_length > 0:
            linear_heat_density = total_annual_demand / total_pipe_length * 1000  # MWh/km
        else:
            linear_heat_density = 0

        # Create metrics dictionary
        metrics = {
            'clusters': '+'.join(map(str, sorted(cluster_set))),
            f'total_annual_{demand_type}_MWh': total_annual_demand,
            'total_pipe_length_m': total_pipe_length,
            f'linear_{demand_type}_density_MWh_per_km': linear_heat_density
        }

        return metrics

    def generate_pipe_layouts(self):
        """
        Generate pipe layouts for all possible combinations of clusters.

        Returns:
        --------
        pd.DataFrame
            DataFrame with metrics for all cluster combinations
        """
        # Generate all possible combinations of clusters
        all_combinations = self.generate_all_cluster_combinations()

        # Calculate metrics for each combination
        all_metrics = []

        # Calculate metrics for cluster 0 alone first
        cluster0_pipes = self.get_required_pipes_for_clusters((0,))
        cluster0_metrics = self.calculate_metrics((0,), cluster0_pipes)
        all_metrics.append(cluster0_metrics)
        log().info(f"Calculated metrics for cluster 0 (existing DTN)")

        for i, cluster_set in enumerate(all_combinations):
            if i % 100 == 0 and i > 0:
                log().info(f"Processed {i}/{len(all_combinations)} cluster combinations")

            # Get required pipes for this set of clusters
            required_pipes = self.get_required_pipes_for_clusters(cluster_set)

            # Calculate metrics
            metrics = self.calculate_metrics(cluster_set, required_pipes)
            all_metrics.append(metrics)

        # Convert to DataFrame
        metrics_df = pd.DataFrame(all_metrics)

        # Save to CSV
        output_file = self.output_folder / "clusters_metrics.csv"
        metrics_df.to_csv(output_file, index=False)
        log().info(f"Saved metrics for {len(all_metrics)} cluster combinations to {output_file}")

        # Return the metrics DataFrame for use by the optimizer
        return metrics_df


def main(config):
    """
    Main function for the DTN expansion optimization.

    Parameters:
    -----------
    config : cea.config.Configuration
        CEA configuration object
    """
    import time
    start_time = time.time()

    # If called from command line, parse arguments
    args = None
    if config is None:
        args = parse_args()
        config = cea.config.Configuration()
        config.scenario = args.scenario

    locator = cea.inputlocator.InputLocator(config.scenario)

    # Get network type from command line or config
    network_type = config.dtn_expansion_optimization.network_type
    if args and args.network_type:
        network_type = args.network_type

    # Get chosen clusters and buildings from command line arguments or config
    chosen_clusters = config.dtn_expansion_optimization.chosen_clusters
    chosen_buildings = config.dtn_expansion_optimization.chosen_buildings

    # Override with command line arguments if provided
    if args:
        if args.chosen_clusters:
            chosen_clusters = args.chosen_clusters
        if args.chosen_buildings:
            chosen_buildings = args.chosen_buildings

    # Determine if we should bypass the prerequisite check
    bypass_check = bool(chosen_clusters or chosen_buildings)

    # Check prerequisites
    if not check_thermal_network_prerequisites(locator, network_type, bypass_check):
        log().error("Prerequisites not met. Results for Thermal Network Part 1 (layout), Part 2 (simulation) with detailed model, and Part 3 (costs) for ALL buildings must first be obtained before running this module.")
        return

    # Perform node and edge clustering
    mapper = ClusterMapper(locator, network_type)
    mapper.write_outputs()

    # Print completion message with computation time
    clustering_time = time.time() - start_time
    log().info(f"DTN nodes and edges clustering completed successfully in {clustering_time:.2f} seconds. Pipe layouts of connecting different sets of building clusters in phase [1] are being generated.")

    # If chosen_clusters is provided, convert it to a list of integers
    if chosen_clusters:
        if isinstance(chosen_clusters, str):
            chosen_clusters = [int(c.strip()) for c in chosen_clusters.split(',') if c.strip()]
        log().info(f"Using chosen clusters: {chosen_clusters}")

    # If chosen_buildings is provided, ensure it's a list
    if chosen_buildings:
        if isinstance(chosen_buildings, str):
            chosen_buildings = [b.strip() for b in chosen_buildings.split(',') if b.strip()]
        log().info(f"Using chosen buildings: {chosen_buildings}")

    # Generate pipe layouts for different sets of clusters
    pipe_layout_generator = PipeLayoutGenerator(
        locator, 
        network_type, 
        phase=1,
        chosen_clusters=chosen_clusters,
        chosen_buildings=chosen_buildings
    )
    metrics_df = pipe_layout_generator.generate_pipe_layouts()

    # Run optimization if requested
    if hasattr(config.dtn_expansion_optimization, 'run_optimization') and config.dtn_expansion_optimization.run_optimization:
        log().info("Starting DTN expansion optimization...")

        # Get optimization parameters from config
        num_phases = config.dtn_expansion_optimization.num_phases if hasattr(config.dtn_expansion_optimization, 'num_phases') else 3

        # Get budget per phase from config
        budget_per_phase = None
        if hasattr(config.dtn_expansion_optimization, 'budget_per_phase') and config.dtn_expansion_optimization.budget_per_phase:
            budget_str = config.dtn_expansion_optimization.budget_per_phase
            if isinstance(budget_str, str):
                budget_per_phase = [float(b.strip()) for b in budget_str.split(',') if b.strip()]

        # Get energy price and interest rate from config
        energy_price = config.dtn_expansion_optimization.energy_price if hasattr(config.dtn_expansion_optimization, 'energy_price') else 0.1
        interest_rate = config.dtn_expansion_optimization.interest_rate if hasattr(config.dtn_expansion_optimization, 'interest_rate') else 0.05

        # Get cost model from config
        cost_model = config.dtn_expansion_optimization.cost_model if hasattr(config.dtn_expansion_optimization, 'cost_model') else 'detailed'

        # Get population size and number of generations from config
        population_size = config.dtn_expansion_optimization.population_size if hasattr(config.dtn_expansion_optimization, 'population_size') else 50
        num_generations = config.dtn_expansion_optimization.num_generations if hasattr(config.dtn_expansion_optimization, 'num_generations') else 30

        # Create optimizer
        optimizer = DTNExpansionOptimizer(
            locator=locator,
            network_type=network_type,
            metrics_df=metrics_df,
            num_phases=num_phases,
            budget_per_phase=budget_per_phase,
            energy_price=energy_price,
            interest_rate=interest_rate,
            cost_model=cost_model
        )

        # Run optimization
        solution = optimizer.optimize(
            population_size=population_size,
            num_generations=num_generations
        )

        # Save results
        optimizer.save_results(solution)

        log().info("DTN expansion optimization completed successfully.")
    else:
        log().info("Optimization not run. To run optimization, use --run_optimization true parameter.")

    # Print final completion message
    total_time = time.time() - start_time
    if not (hasattr(config.dtn_expansion_optimization, 'run_optimization') and config.dtn_expansion_optimization.run_optimization):
        log().info("Note: Optimization was not run. To run optimization, use --run_optimization true parameter.")
    log().info(f"DTN expansion optimization completed successfully in {total_time:.2f} seconds.")

if __name__ == "__main__":
    main(None)
