#!/usr/bin/env python3
"""
DTN_expansion_optimization.py
=============================
A workflow to stage the expansion of an existing (cluster‑0) District Thermal
Network (DTN) into an arbitrary number of *phases* while maximising a financial
objective (ROI, NPV or simple pay‑back).

Key design philosophy
---------------------
* **Single network layout** – we reuse the *Part 1* master layout that connects
  **all** candidate buildings.  This avoids having to regenerate geometry for
  each phase and ensures pipe positions & diameters stay consistent.
* **Edge activation** – every pipe (edge) in that master graph carries a
  Boolean `active` flag.  When a cluster is assigned to a phase we activate the
  path that links its nodes to the already‑active network.  CAPEX is charged
  *only once* per edge – the phase that first activates it.
* **Modular optimization layer** – the cost / hydraulic model is kept strictly
  separate from the search algorithm.  You may plug‑in Greedy, A*, Genetic
  Algorithm, etc. simply by switching the `choose_next_phase()` strategy.
* **CEA integration ready** – inputs are read via `cea.inputlocator.InputLocator`
  and parameters via `cea.config.Configuration`.  The script therefore runs
  seamlessly from the CEA CLI or Dashboard once registered in `scripts.yml`.
  --------------------
 **REV 6 – _node / edge clustering only_**

This revision does **one thing only**: it maps every *node* and *edge* of an
existing Part‑1 network layout to the building–clusters generated by
`building_clustering.py` and stores the result as CSV.  No phasing, no CAPEX
math yet – those will follow in later revisions once this data layer is rock
solid.

Output files written to
`{scenario}/outputs/data/optimization/dtn_expansion/`  ▸

* `cluster_nodes.csv` → one row per node, with its cluster id and role
  (CONSUMER / PLANT / OTHER)
* `cluster_edges.csv` → one row per edge, with:
    * `edge_id` (taken from `edges.shp` *Name* attribute if present, or a
      synthetic id)
    * `cluster_src` / `cluster_dst` – cluster of each incident node
    * `intra_cluster` (1 if src==dst)
      └─ those edges are considered “owned” by that cluster
    * length [m], diameter [mm], material, etc. (copied verbatim from shp)

These two CSVs form the basis for any later CAPEX or phasing logic.
"""

from __future__ import annotations

###############################################################################
# 1) STANDARD IMPORTS                                                        #
###############################################################################
import argparse
import logging
from pathlib import Path
from typing import Dict, Tuple

import geopandas as gpd
import pandas as pd
import networkx as nx

import cea.config               # type: ignore
import cea.inputlocator         # type: ignore

###############################################################################
# 2) LOGGING                                                                 #
###############################################################################

def log()->logging.Logger:
    lg = logging.getLogger("cea.dtn_expansion")
    if not lg.handlers:
        logging.basicConfig(level=logging.INFO,
                            format="%(asctime)s | %(levelname)5s | %(message)s",
                            datefmt="%H:%M:%S")
    return lg

###############################################################################
# 3) HELPERS                                                                 #
###############################################################################

def _read_shp_force_2d(path: Path) -> gpd.GeoDataFrame:
    """Load shapefile and drop Z‑coords that sometimes sneak in."""
    gdf = gpd.read_file(path)
    if gdf.geometry.iloc[0].has_z:
        gdf["geometry"] = gdf.geometry.apply(lambda g: type(g)([(x, y) for x, y, *_ in g.coords]))
    return gdf

###############################################################################
# 4) CORE SCRIPT                                                             #
###############################################################################

class ClusterMapper:
    """Map nodes / edges ➜ cluster ids using Edge‑Node incidence matrix."""

    def __init__(self, locator: cea.inputlocator.InputLocator, net_type:str):
        self.loc = locator
        self.net_type = net_type
        self._load_inputs()
        self._build_lookup()

    # ------------------------------------------------------------------
    def _load_inputs(self):
        # clusters from building_clustering
        path_cl = Path(self.loc.get_dtn_cluster_assignment_file())
        self.df_clusters = pd.read_csv(path_cl)
        log().info("Building clusters loaded: %d buildings", len(self.df_clusters))

        # nodes & edges shapefiles (Part‑1 output)
        nodes_shp = Path(self.loc.get_network_layout_nodes_shapefile(self.net_type))
        edges_shp = nodes_shp.with_name("edges.shp")
        self.gdf_nodes = _read_shp_force_2d(nodes_shp)
        self.gdf_edges = _read_shp_force_2d(edges_shp)
        log().info("Network layout: %d nodes, %d edges", len(self.gdf_nodes), len(self.gdf_edges))

        # Edge‑Node incidence exported by Part‑2 (CSV)
        inc_csv = Path(self.loc.scenario)/"outputs"/"data"/"thermal-network"/f"{self.net_type}__EdgeNode.csv"
        self.df_inc = pd.read_csv(inc_csv, index_col=0)
        log().info("Edge–Node incidence matrix: %s × %s", *self.df_inc.shape)

    # ------------------------------------------------------------------
    def _build_lookup(self):
        # map building name ➜ cluster id
        building2cid: Dict[str,int] = dict(self.df_clusters[["name","cluster"]].values)

        # node ➜ cluster
        cid_col = []
        for _,row in self.gdf_nodes.iterrows():
            if row.get("type","").upper()=="CONSUMER":
                bld = row.get("building") or row.get("name")
                cid = building2cid.get(str(bld), -99)
            elif row.get("type","").upper()=="PLANT":
                cid = 0   # existing DTN
            else:
                cid = -1  # undefined / street intersection etc.
            cid_col.append(cid)
        self.gdf_nodes["cluster"] = cid_col

        # edge ➜ clusters of its two incident nodes
        # Use incidence matrix to get node list per edge quickly
        edge_ids = self.df_inc.columns.tolist()
        node_index = list(self.df_inc.index)
        src_cid = []; dst_cid = []
        for eid in edge_ids:
            vec = self.df_inc[eid]
            nodes = [node for node,val in vec.items() if val!=0]
            if len(nodes)!=2:
                src_cid.append(-1); dst_cid.append(-1); continue
            n1,n2 = nodes
            cid1 = int(self.gdf_nodes.loc[self.gdf_nodes["name"]==n1,"cluster"].values[0])
            cid2 = int(self.gdf_nodes.loc[self.gdf_nodes["name"]==n2,"cluster"].values[0])
            src_cid.append(cid1); dst_cid.append(cid2)
        self.gdf_edges["cluster_src"] = src_cid
        self.gdf_edges["cluster_dst"] = dst_cid
        self.gdf_edges["intra_cluster"] = (self.gdf_edges.cluster_src == self.gdf_edges.cluster_dst).astype(int)

    # ------------------------------------------------------------------
    def write_outputs(self):
        out_folder = Path(self.loc.get_dtn_expansion_optimization_results_folder())
        out_folder.mkdir(parents=True, exist_ok=True)
        # nodes
        nodes_out = self.gdf_nodes[["name","type","building","cluster"]]
        nodes_out.to_csv(out_folder/"cluster_nodes.csv", index=False)
        # edges
        cols_basic = [c for c in ("Name","length_m","D_int_m","material","cluster_src","cluster_dst","intra_cluster") if c in self.gdf_edges.columns]
        self.gdf_edges[cols_basic].to_csv(out_folder/"cluster_edges.csv", index=False)
        log().info("CSV written › %s", out_folder)

###############################################################################
# 5) CLI ENTRY                                                               #
###############################################################################

def main():
    ap = argparse.ArgumentParser(description="Assign network nodes / edges to building clusters")
    ap.add_argument("scenario", help="CEA scenario root folder")
    ap.add_argument("--network-type", choices=["DH","DC"], default="DH")
    args = ap.parse_args()

    cfg = cea.config.Configuration(); cfg.scenario = args.scenario
    locator = cea.inputlocator.InputLocator(cfg.scenario)

    mapper = ClusterMapper(locator, args.network_type)
    mapper.write_outputs()

if __name__ == "__main__":
    main()
